### ISSUE TITLE
Running IOpipe on Windows fails due to lack of support in SystemMeasurement

### ISSUE THREAD

**Issue by XerTheSquirrel** [iopipe/iopipe-java#153]
Running `mvn test` fails because `SystemMeasurement` does not support Windows so the measuring fails to work properly and as such the invocations fail.

```
ERROR: Test threw an exception!: java.lang.NumberFormatException: double value cannot be Infinite or NaN                        
        at org.glassfish.json.JsonGeneratorImpl.write(JsonGeneratorImpl.java:217)                                               
        at com.iopipe.IOpipeExecution.__buildRequest(IOpipeExecution.java:532)                                                  
        at com.iopipe.IOpipeService.run(IOpipeService.java:437)                                                                 
```

Related to #154.

**Comment by XerTheSquirrel** [comment]
For #154 / #157 I tested this on Windows and an exception is no longer thrown and all the tests pass.

Can I get a thought on this @pselle, do we invalidate this issue or do we add support for Windows in the system measurements? I know Windows is not supported for AWS right now.

Screenshot of the test passing:
![screenshot_20180829_113459](https://user-images.githubusercontent.com/11927855/44798485-94c5fe00-ab7f-11e8-876e-bd715d9d3eab.png)

The JSON of a request looks like this:
```json
{
    "client_id": "ThisIsNotARealIOpipeTokenAndIsUsedForTesting",
    "installMethod": "unknown",
    "processId": "015a63df-8c27-49d6-8be4-9a6a5e6f0060",
    "timestamp": 1535556659525,
    "timestampEnd": 1535556659577,
    "aws": {
        "functionName": "mock-objtrans-arrayintegerXjs",
        "functionVersion": "1.0",
        "awsRequestId": "00000000-0000-0000-0000-000000000000",
        "invokedFunctionArn": "mock-objtrans-arrayintegerXjs",
        "logGroupName": "mockloggroupname",
        "logStreamName": "mocklogstreamname",
        "memoryLimitInMB": 1024,
        "getRemainingTimeInMillis": 2948,
        "traceId": "unknown"
    },
    "disk": {
        "totalMiB": 0.0,
        "usedMiB": 0.0,
        "usedPercentage": 100.0
    },
    "environment": {
        "agent": {
            "runtime": "java",
            "version": "1.7.0",
            "load_time": 1535556644929
        },
        "runtime": {
            "name": "java",
            "version": "1.8.0_181",
            "vendor": "Oracle Corporation",
            "vmVendor": "Oracle Corporation",
            "vmVersion": "25.181-b13"
        },
        "host": {
            "boot_id": "unknown"
        },
        "os": {
            "hostname": "unknown",
            "totalmem": 0,
            "freemem": 0,
            "usedmem": 0,
            "cpus": []
        }
    },
    "coldstart": false,
    "custom_metrics": [{
        "name": "source.class",
        "s": "java.util.ArrayList"
    }, {
        "name": "source.value",
        "s": "[1, 2, 3, 4]"
    }, {
        "name": "target.class",
        "s": "[Ljava.lang.String;"
    }, {
        "name": "target.value",
        "s": "[Ljava.lang.String;@2b9ed6da"
    }],
    "performanceEntries": [],
    "labels": ["@iopipe/metrics"],
    "plugins": [{
        "name": "test",
        "version": "1.0.0",
        "homepage": "https://github.com/iopipe/iopipe-java",
        "enabled": false
    }, {
        "name": "trace",
        "version": "1.2.0",
        "homepage": "https://github.com/iopipe/iopipe-java",
        "enabled": false
    }, {
        "name": "profiler",
        "version": "1.2.1",
        "homepage": "https://github.com/iopipe/iopipe-java",
        "enabled": false
    }, {
        "name": "event-info",
        "version": "1.2.0",
        "homepage": "https://github.com/iopipe/iopipe-java",
        "enabled": false
    }],
    "duration": 51918566
}
```

**Comment by pselle** [comment]
@XerTheSquirrel Let's close, because this is only an issue for local dev/test, since we're supporting AWS Lambda.
