### ISSUE TITLE
`NullPointerException` in statistics/profiler code.

### ISSUE THREAD

**Issue by XerTheSquirrel** [iopipe/iopipe-java#96]
This is a non-fatal exception, IOpipe still records and sends events but if this occurs then the profiler plugin does not report anything (that is even if profiling is enabled the dashboard for that event will just say that no profiler information is available). I have only seen this once but it appears that it is possible for the statistics part of the profiler to throw an exception. Since this is related to the thread statistics code I am going to guess that a thread was destroyed in the middle of gathering statistics for it which could be why this exception is thrown. I picked up this from seeing if the release plugin works

It seems like the pre-execution fails which then causes the post-execution to fail too when the thread statistic snapshot could not be created.

Logs and traces:
```
[INFO] 16:06:15.012 [main] DEBUG com.iopipe.Engine - >>> BEGIN TEST: mock-profilerplugin
[INFO] 16:06:15.013 [main] DEBUG com.iopipe.IOpipeService - Invoking context 6cd28fa7
[INFO] 16:06:15.024 [IOpipe-ProfilerGetURL] DEBUG com.iopipe.plugin.profiler.ProfilerExecution - Profiler URL: https://localhost/profiler
[INFO] 16:06:15.026 [IOpipe-ProfilerGetURL] DEBUG com.iopipe.plugin.profiler.ProfilerExecution - Got upload URL: https://localhost/profiler-result
[INFO] 16:06:15.026 [IOpipe-ProfilerGetURL] DEBUG com.iopipe.plugin.profiler.ProfilerExecution - Got access token: token
[INFO] 16:06:15.027 [IOpipe-ProfilerGetURL] DEBUG com.iopipe.plugin.profiler.ProfilerExecution - Signer sent: {result=201, type=application/json; charset=utf-8, body=109 bytes} {"signedRequest":"https://localhost/profiler-result", "jwtAccess":"token", "url":"http://localhost/snapshot"}
[INFO] 16:06:15.027 [main] ERROR com.iopipe.IOpipeService - Could not run pre-executable plugin.
[INFO] java.lang.NullPointerException: null
[INFO]  at com.iopipe.plugin.profiler.ThreadStatistics.snapshots(ThreadStatistics.java:156) ~[classes/:?]
[INFO]  at com.iopipe.plugin.profiler.ThreadStatistics.snapshots(ThreadStatistics.java:99) ~[classes/:?]
[INFO]  at com.iopipe.plugin.profiler.ManagementStatistics.snapshot(ManagementStatistics.java:129) ~[classes/:?]
[INFO]  at com.iopipe.plugin.profiler.ProfilerExecution.__pre(ProfilerExecution.java:447) ~[classes/:?]
[INFO]  at com.iopipe.plugin.profiler.ProfilerPlugin.preExecute(ProfilerPlugin.java:82) ~[classes/:?]
[INFO]  at com.iopipe.IOpipeExecution.plugin(IOpipeExecution.java:313) ~[classes/:?]
[INFO]  at com.iopipe.IOpipeService.run(IOpipeService.java:255) ~[classes/:?]
[INFO]  at com.iopipe.Engine.__run(Engine.java:176) ~[test-classes/:?]
[INFO]  at com.iopipe.Engine.lambda$generateTests$17(Engine.java:256) ~[test-classes/:?]

....................

[INFO] 16:06:16.755 [main] ERROR com.iopipe.IOpipeService - Could not run post-executable plugin.
[INFO] java.lang.NullPointerException: null
[INFO]  at com.iopipe.plugin.profiler.ProfilerExecution.__post(ProfilerExecution.java:187) ~[classes/:?]
[INFO]  at com.iopipe.plugin.profiler.ProfilerPlugin.postExecute(ProfilerPlugin.java:96) ~[classes/:?]
[INFO]  at com.iopipe.IOpipeExecution.plugin(IOpipeExecution.java:313) ~[classes/:?]
[INFO]  at com.iopipe.IOpipeService.run(IOpipeService.java:303) ~[classes/:?]
[INFO]  at com.iopipe.Engine.__run(Engine.java:176) ~[test-classes/:?]
[INFO]  at com.iopipe.Engine.lambda$generateTests$17(Engine.java:256) ~[test-classes/:?]
```

**Comment by XerTheSquirrel** [comment]
Found this bug in the wild on this CircleCI build: <https://circleci.com/gh/XerTheSquirrel/iopipe-java/40?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link>.
